app1/urls.py
from django.urls import path
from app1 import views
app_name='app1' #access another page by link
urlpatterns = [
    path('header/',view=views.header,name='header'),
    path('',view=views.home,name='home'),
    path('about/',view=views.about,name='about'),
    path('event/',view=views.event,name='event'),
    path('contact/',view=views.contact,name='contact'),
    path('admission/',view=views.admission,name='admission'),
    path('formdata/',view=views.formdata,name='formdata'),
    path('delete/<int:id>/',view=views.delete_data,name='deletedata'),
    # path('teacher/',view=views.teacher,name='teacher'),
    path('student/',view=views.student,name='student'),
    path('login/',view=views.login,name='login'),


    #syllabus dropwown
    path('cls1/',view=views.cls1,name='cls1'),
    path('cls2/',view=views.cls2,name='cls2'),
    path('cls3/',view=views.cls3,name='cls3'),
    path('cls4/',view=views.cls4,name='cls4'),
    path('cls5/',view=views.cls5,name='cls5'),


]

schoolproject/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import delete_data,update_data,home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('delete/<int:id>/',view=delete_data,name='deletedata'),
    path('update/<int:id>/',view=update_data,name='updatedata'),
    path('',view=home,name='home'),

]

app1/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    Student_Name=models.CharField(max_length=50)
    # Teacher_Name=models.CharField(max_length=50)
    Mother_Name=models.CharField(max_length=50)
    Adhar_No=models.IntegerField(max_length=50)
    Contact_No=models.IntegerField(max_length=50)
    Address=models.CharField(max_length=50)
    # Salary=models.IntegerField(max_length=50,default=10000)
    # Subject=models.CharField(max_length=30,default='maths')

class Teacher(models.Model):
    Teacher_Name=models.CharField(max_length=50)
    Subject=models.CharField(max_length=30)    
    Salary=models.IntegerField(max_length=50,default=10000)
    Contact_No=models.IntegerField(max_length=50)

app1/forms.py
from .models import Student
from django.forms import ModelForm
# from django.core import validators
from django import forms

class StudentForm(forms.ModelForm):
    class Meta:
        model=Student
        fields=['Student_Name','Mother_Name','Adhar_No','Contact_No','Address']
        widgets={
            'Student_Name':forms.TextInput(attrs={'class':'form-control'}),
            'Mother_Name':forms.TextInput(attrs={'class':'form-control'}),
            'Adhar_No':forms.TextInput(attrs={'class':'form-control'}),
            'Contact_No':forms.TextInput(attrs={'class':'form-control'}),
            'Address':forms.TextInput(attrs={'class':'form-control'})
        }
        fields=['Student_Name','Mother_Name','Adhar_No','Contact_No','Address']

# class TeacherForm(StudentForm):
#     class Meta(StudentForm.Meta):
#         #fields=['Teacher_Name','Subject','Adhar_No','Contact_No','Address','Salary']
#         fields=['Teacher_Name','Subject','Salary','Contact_No']


# class LoginForm(TeacherForm):
#     class Meta(TeacherForm.Meta):
#         fields=['Contact_No',]

app1/views.py
from django.shortcuts import render,HttpResponseRedirect
from .models import Student
from .forms import StudentForm
from django.core import validators

# Create your views here.
def header(request):
    return render(request=request,template_name='header.html')

def home(request):
    return render(request=request,template_name='home.html')

def about(request):
    return render(request=request,template_name='about.html')

def event(request):
    return render(request=request,template_name='event.html')

def login(request):
    return render(request=request,template_name='login.html')

def contact(request):
    return render(request=request,template_name='contact.html')

def admission(request):
    return render(request=request,template_name='admission.html')

# def login(request):
#     return render(request=request,template_name='login.html')

# add data using form
def formdata(request):
    if request.method=='POST':
        fm=StudentForm(request.POST)
        if fm.is_valid():
            fm.save() #sort way to save
        # if fm.is_valid():
        #     nm=fm.changed_data['Student_Name']
        #     mn=fm.cleaned_data['Mother_Name']
        #     adrn=fm.cleaned_data['Adhar_No']
        #     cnt=fm.cleaned_data['Contact_No']
        #     adrs=fm.cleaned_data['Address']
        #     res=AdmissionForm(Student_Name=nm,Mother_Name=mn,Adhar_No=adrn,Contact_No=cnt,Address=adrs)
        #     res.save()
            return render(request=request,template_name="sucessfuladmsn.html")
        fm=StudentForm()
    else:
        fm=StudentForm()
    stud=Student.objects.all()    # show all formdata
    return render(request=request,template_name='1.html',context={'form':fm,'stu':stud})

    # delete data
def delete_data(request,id):
    if request.method=='POST':
        pi=Student.objects.get(pk=id)
        pi.delete()
        return HttpResponseRedirect('/') #delete from home


#udpate or edit
def update_data(request,id):
    if request.method=='POST':
        pi=Student.objects.get(pk=id)
        fm=StudentForm(request.POST,instance=pi)
        if fm.is_valid():
            fm.save()
    else:
        pi=Student.objects.get(pk=id)
        fm=StudentForm(instance=pi)
    return render(request=request,template_name='update.html',context={'form':fm})


#Student details
def student(request):
    if request.method=='POST':
        fm=StudentForm(request.POST)
        fm=(request.POST)
        if fm.is_valid():
            fm.save()
    else:
        fm=StudentForm()
    return render(request=request,template_name='teacher.html',context={'form':fm})


#teacher details
# def teacher(request):
#     if request.method=='POST':
#         fm=TeacherForm(request.POST)
#         if fm.is_valid():
#             fm.save()
#     else:
#         fm=TeacherForm()
#     return render(request=request,template_name='teacher.html',context={'form':fm})

# #login
# def login(request):
#     if request.method=='POST':
#         fm=LoginForm(request.POST)
#         if fm.is_valid():
#             fm.save()
#     else:
#         fm=LoginForm()
#     return render(request=request,template_name='login.html',context={'form':fm})

#class Dropdown
def cls1(request):
    return render(request=request,template_name='cls1.html')

def cls2(request):
    return render(request=request,template_name='cls2.html')

def cls3(request):
    return render(request=request,template_name='cls3.html')

def cls4(request):
    return render(request=request,template_name='cls4.html')

def cls5(request):
    return render(request=request,template_name='cls5.html')

app1/templates/about.html
<!DOCTYPE html>
{% load static %} 
{% load bootstrap5 %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/about.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>

      {% include 'header.html' %}

    
    





      {% comment %} <!-- nav -->

    <ul class="nav justify-content-end bg-danger w-100 p-3 text-white bg-dark">
      <li class="nav-item">
        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'app1:home' %}"
          width="100px"
          height="100%"
          >HOME</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:about' %}">ABOUT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:admission' %}">ADMISSION</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:event' %}">EVENTS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:login' %}">LOGIN</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:contact' %}">CONTACT US</a>
      </li>
    </ul> {% endcomment %}
    
    <!-- page-1 -->

    <div class="container">
      <div class="left">
        <img src="{% static 'images/sports.png' %}" alt="" />
      </div>
      <div class="right">
        <h1 id="sf">Sports Facility</h1>
        <br />
        <hr id="hr" />
        <p>
          We are proud to offer a state-of-the-art sports facility at our
          school, providing our students with opportunities to engage in
          physical activity and develop their athletic abilities.Our sports
          facility includes a range of equipment and amenities, including
          outdoor fields for team sports such as soccer, football, and baseball.
          We also have basketball and tennis courts for individual or team play,
          as well as a track for running and other athletic activities.Inside
          our facility, we have a spacious gymnasium for indoor sports and
          activities like basketball, volleyball, and gymnastics. Our gym also
          includes a weight room and fitness equipment for students to use
          during their workouts.In addition to our extensive sports equipment,
          we also have dedicated coaches and trainers who work with our students
          to help them achieve their athletic goals. Our coaches are passionate
          about sports and work hard to ensure that each student has the
          opportunity to develop their skills and abilities to their full
          potential.
        </p>
      </div>
    </div>


    <!-- page-2 -->
    <div class="container">
      <div class="left">
        <img src="{% static 'images/library.png' %}" alt="" />
      </div>
      <div class="right">
        <h1 id="sf">Library Facility</h1>
        <br />
        <hr id="hr" />
        <p>
          At our school, the library is a hub of learning, exploration, and
          discovery. We are proud to offer a state-of-the-art library facility
          that is designed to meet the needs of all our students. Our library
          features a wide range of books, magazines, and other printed
          materials, as well as access to a variety of online resources and
          databases. Our librarians are dedicated professionals who are always
          available to help students find the resources they need and answer any
          questions they may have.In addition to providing resources for
          learning and research, the library also offers a comfortable and quiet
          space for students to study, work on projects, or simply relax and
          read. With comfortable seating, ample natural light, and a calm
          atmosphere, the library is the perfect place to escape the noise and
          distractions of the outside world and focus on academic and personal
          pursuits. At our school, we believe that the library is an essential
          component of the education experience. It provides students with the
          tools and resources they need to succeed academically, while also
          fostering a love of learning and curiosity that extends beyond the
          classroom. We are proud to offer a top-notch library facility that
          supports the educational and personal growth of our students and
          promotes a lifelong love of reading and learning.
        </p>
      </div>
    </div>
    <!-- page-3 -->
    <div class="container">
      <div class="left">
        <img src="{% static 'images/bus.png' %}" alt="" />
      </div>
      <div class="right">
        <h1 id="sf">Bus Facility</h1>
        <br />
        <hr id="hr" />
        <p>
          At our school, we understand the importance of safe and reliable
          transportation for our students. That’s why we offer a comprehensive
          transport facility that is designed to meet the needs of our families
          and students.Our transport facility includes a fleet of
          well-maintained buses that are equipped with modern safety features,
          including seat belts, GPS tracking, and on-board cameras. Our drivers
          are highly trained and experienced, and they take great care to ensure
          that all students are transported safely to and from school.We offer
          transportation services to students who live within a designated area
          surrounding our school. Our routes are designed to be convenient for
          our families, with multiple stops throughout the surrounding
          neighbourhood.In addition to providing safe and reliable
          transportation, we also believe in promoting positive behaviour and
          responsibility among our students.
        </p>
      </div>
    </div>
    <!-- page-4 -->
    <div class="container">
      <div class="left">
        <img src="{% static 'images/computerlab.png' %}" alt="" />
      </div>
      <div class="right">
        <h1 id="sf">Computer Lab</h1>
        <br />
        <hr id="hr" />
        <p>
          At our school, we are proud to offer a state-of-the-art computer lab
          facility that is designed to support student learning and engagement
          in technology. Our computer lab is equipped with advanced hardware and
          software that allow students to explore a wide range of digital tools
          and applications. Our computer lab provides students with access to
          the latest technology and resources that help to enhance their
          academic experience. With internet access and a variety of educational
          software programs, our students can learn, explore and experiment with
          the latest technologies. Our computer lab is also staffed by
          experienced technicians who are available to help students with any
          technical issues or questions they may have. Whether students need
          help navigating software or troubleshooting hardware issues, our
          technicians are there to help. In addition to offering a wide range of
          technology resources, our computer lab also provides a safe and secure
          environment for students to learn and experiment with technology. With
          a dedicated space and controlled access, students can use the lab
          safely and responsibly.
        </p>
      </div>
    </div>
    <!-- page-5 -->
    <div class="container">
      <div class="left">
        <img src="{% static 'images/smartclass.png' %}" alt="" />
      </div>
      <div class="right">
        <h1 id="sf">Smart Class</h1>
        <br />
        <hr id="hr" />
        <p>
          Our school is proud to offer state-of-the-art smart class facilities
          that enhance the learning experience for our students. With advanced
          technology, interactive displays, and multimedia tools, our smart
          classrooms offer a more engaging, dynamic, and personalized approach
          to learning.Our smart class facilities are equipped with the latest
          tools and resources, including projectors, interactive whiteboards,
          and digital displays. This technology allows teachers to create
          interactive and immersive learning experiences that capture the
          attention and imagination of our students.The multimedia capabilities
          of smart classrooms allow students to explore concepts and ideas in
          new and exciting ways. They can watch videos, participate in virtual
          simulations, and interact with digital content that brings lessons to
          life. This type of learning can help students understand concepts more
          deeply and retain information more effectively
        </p>
      </div>
    </div>
    {% include 'footer.html' %}
  </body>
</html>

app1/templates/admission.html
<!DOCTYPE html>
{% load static %} 
{% load bootstrap5 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/admission.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
</head>
<body>
    <!-- {% include 'header.html' %} -->

    <!-- drop down -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-center">
      <div class="container-fluid">
        <!-- <a class="navbar-brand" href="#">Navbar</a> -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown ">
              <a id="dropdown" class="nav-link dropdown-toggle fw-bolder " href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Syllabus
              </a>
              <ul id="dropdown" class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'app1:cls1' %}">1</a></li>
                <li><a class="dropdown-item" href="{% url 'app1:cls2' %}">2</a></li>
                <li><a class="dropdown-item" href="{% url 'app1:cls3' %}">3</a></li>
                <li><a class="dropdown-item" href="{% url 'app1:cls4' %}">4</a></li>
                <li><a class="dropdown-item" href="{% url 'app1:cls5' %}">5</a></li>


              </ul>
              <li class="nav-item dropdown ">
                <a id="dropdown" class="nav-link dropdown-toggle fw-bolder " href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Class
                </a>
                <ul id="dropdown" class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'app1:formdata' %}">1</a></li>
                  <li><a class="dropdown-item" href="{% url 'app1:formdata' %}">2</a></li>
                  <li><a class="dropdown-item" href="#">3</a></li>
                  <li><a class="dropdown-item" href="#">4</a></li>
                  <li><a class="dropdown-item" href="#">5</a></li>
  
  
                </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    
    <!-- cart -->
    <!-- <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
          <div class="card h-100">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
            <div class="card-footer">
              <small class="text-body-secondary">Last updated 3 mins ago</small>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card h-100">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
            </div>
            <div class="card-footer">
              <small class="text-body-secondary">Last updated 3 mins ago</small>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card h-100">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
            </div>
            <div class="card-footer">
              <small class="text-body-secondary">Last updated 3 mins ago</small>
            </div>
          </div>
        </div>
      </div> -->

      <!-- {% include 'footer.html' %} -->

</body>
</html>

app1/templates/contact.html
<!DOCTYPE html>
{% load static %} 
{% load bootstrap5 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script> 
    <style>

</style>
</head>
<body>
  {% include 'header.html' %}
  
  
    



  
{% comment %} image {% endcomment %}
          <img class="photo mt-3" src="{% static 'images/classroom1.jpeg' %}" alt="">

    <footer id="foot" class="text-center text-lg-start bg-body-tertiary mt-0 text-muted">
        <!-- Section: Social media -->
        <section
          class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
          <!-- Left -->
          <div class="me-5 d-none d-lg-block">
          </div>
          <!-- Left -->

          <!-- Right -->
          <div>
            <a
              href="https://www.instagram.com/"
              target="_blank"
              class="me-4 text-reset"
            >
              <i class="fab fa-facebook-f"
                ><img
                  src="{% static 'images/instalogo.png' %}"
                  alt=""
                  height="40px"
              /></i>
            </a>
            <a href="https://www.facebook.com/" class="me-4 text-reset">
              <i class="fab fa-twitter"><img  src="{% static 'images/fblogo.png' %}" alt="" height="40px"/></i>
            </a>
            <a href="https://www.linkedin.com/feed/" class="me-4 text-reset">
              <i class="fab fa-google"><img  src="{% static 'images/linkdinlogo.png' %}" alt="" height="40px"/></i>
            </a>
            <a href="https://www.youtube.com/" class="me-4 text-reset">
              <i class="fab fa-instagram"><img  src="{% static 'images/youtubelogo.png' %}" alt="" height="40px"/></i>
            </a>
            <a href="" class="me-4 text-reset">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
              <i class="fab fa-github"></i>
            </a>
          </div>
          <!-- Right -->
        </section>
        <!-- Section: Social media -->

        <!-- Section: Links  -->
        <section class="">
          <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
              <!-- Grid column -->
              <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fs-3 fw-bold mb-4">
                  <i class="fas fa-gem   me-3"></i>XYZ School
                </h6>
                <p class="fs-3" >
                  Here you can use rows and columns to organize your footer
                  content. Lorem ipsum dolor sit amet, consectetur adipisicing
                  elit.
                </p>
              </div>
             
              <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fs-3 fw-bold mb-4">Useful links</h6>
                <p class="useful-link">
                  <a class="fs-3" href="{% url 'app1:home' %}" class="text-reset">Home</a>
                </p>
                <p>
                  <a class="fs-3"  href="{% url 'app1:admission' %}" class="text-reset">Admission</a>
                </p>
                <p>
                  <a class="fs-3"  href="{% url 'app1:about' %}" class="text-reset">About</a>
                </p>
                <p>
                  <a class="fs-3"  href="{% url 'app1:contact' %}" class="text-reset">Contact</a>
                </p>
              </div>
              <!-- Grid column -->

              <!-- Grid column -->
              <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fs-3  fw-bold mb-4">Contact</h6>
                <p class="fs-3"><i class="fas fa-home me-3"></i> XYZ School, Patna</p>
                <p class="fs-3">
                  <i class="fas  fa-envelope me-3"></i><a id="mail-link" href="">xyzinfo@example.com</a>
                </p>
                <p class="fs-3"><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                <p class="fs-3"><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
              </div>
              
              <!-- Grid column -->
            </div>
            <!-- Grid row -->
          </div>
        </section>
        <!-- Section: Links  -->

        <!-- Copyright -->
        <div
          class="text-center p-4"
          style="background-color: rgba(101, 10, 10, 0.05)"
        >
          © 2021 Copyright:
          <a class="text-reset fw-bold" href="https://xyx.com/">xyz.com</a>
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
  </body>
</html>

app1/templates/header.html
<!DOCTYPE html>
{% load static %} {% load bootstrap5 %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <ul class="nav justify-content-end bg-danger w-100 p-3 text-white bg-dark cur">
      <li class="nav-item">
        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'app1:home' %}"
          width="100px"
          height="100%"
          >HOME</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:about' %}">ABOUT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:admission' %}">ADMISSION</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:event' %}">EVENTS</a>
      </li>
      <li class="nav-item">
        <div class="dropdown">
          <a class="btn btn-primary dropdown-toggle" href="{% url 'app1:login' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Login
          </a>
          
          <ul class="dropdown-menu text-dark">
            <li><a class="dropdown-item " href="#">Student</a></li>
            <li><a class="dropdown-item" href="#">Teacher</a></li>
          </ul>
        </div>
      </li>
      
       




      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:contact' %}">CONTACT US</a>
      </li>

      
    </ul>
  </body>
</html>

app1/templates/sllabus/1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>CBSE Class 2 Syllabus 2023-24 All Subjects</h2>
    <p>The Central Board of Secondary Education holds the title of India’s most prominent national educational board and has successfully generated syllabi that guarantee a bright future. The CBSE class 2 syllabus 2023-24 has been modified, keeping in mind the learning capability of a 2nd grader.

        The most important aspect of the syllabus revised by the CBSE board is the playful nature of the chapters, some of which are filled with mind games and puzzles. It is designed to sharpen and develop the minds of the students. The CBSE class 2 syllabus can be easily aced with the help of various study materials provided by CBSE such as CBSE revision notes, CBSE sample papers, CBSE extra questions, etc. </p>
</body>
</html>